service:
  name: way-pages-api

package:
  individually: true

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-dynamodb-local
  - serverless-offline
  - serverless-dotenv-plugin

provider:
  name: aws
  region: sa-east-1
  runtime: nodejs10.x
  stage: local
  versionFunctions: false # No functions versioning

  environment:
    SERVICE_PREFIX: ${self:custom.prefix}
    DYNAMODB_TABLE: ${self:custom.dynamoTable}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - "Fn::GetAtt": [DynamoDBTable, Arn]
        - Fn::Join:
            - "/"
            - - { "Fn::GetAtt": [DynamoDBTable, Arn] }
              - "index/*"

custom:
  region: ${self:provider.region}
  stage: ${opt:stage, self:provider.stage}
  prefix: ${self:custom.stage}-${self:service}
  dynamoTable: ${self:custom.prefix}-table

  serverless-offline:
    host: "0.0.0.0"
    port: 3001

  webpack:
    includeModules:
      forceExclude:
        - aws-sdk

  dynamodb:
    stages:
      - local
    start:
      port: 8000
      heapInitial: 200m
      heapMax: 1g
      dbPath: ${env:PWD}/tmp
    # noStart: true

functions: ${file(serverless-handlers.js)}

resources:
  # DynamoDB
  - ${file(resources/dynamodb-table.yml)}
